# Dependencies
markdown:         redcarpet
highlighter:      true

# Site settings
title: SuprAcademy
email: your-email@domain.com
description: ""
baseurl: ""
url: "http://supracademy.com"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - 'node_modules'
  - 'package.json'
