# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Site settings
title: SuprAcademy
email: info@supracademy.com
description: ""
baseurl: ""
url: "http://supracademy.com"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - 'node_modules'
  - 'package.json'
