# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Site settings
title: SuprAcademy
email: info@supracademy.com
description: ""
baseurl: ""
url: "http://supracademy.com"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - 'node_modules'
  - 'package.json'

excerpt_separator: <!–break–>

prose:
  rooturl: "_posts"
  siteurl: "https://supracademy.com"
  media: "assets/posts"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          element: "date"
          value: "CURRENT_DATETIME"

